import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY
const supabaseReady = !!(SUPABASE_URL && SUPABASE_ANON_KEY)
const supabase = supabaseReady ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null
const app = document.querySelector('#app')
const SESSION_KEY='mi_porra_session_clean_v1'

let currentUser=null,currentPool=null,tab='porras'
let users=[],pools=[],poolMembers=[],matches=[],predictions=[],messages=[],teamPlayers=[]
const ADMIN_NICK='admin', ADMIN_PASSWORD='968085070'

function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function avatar(u){return `<span style="display:inline-block;width:28px;height:28px;text-align:center;line-height:28px;background:#dcfce7;border-radius:6px;margin-right:8px">${safe(u?.avatar||'⚽')}</span>`}
function generateCode(){return Math.random().toString(36).substring(2,8).toUpperCase()}
function sign(a,b){return a>b?1:a<b?2:'X'}
function basePoints(ph,pa,rh,ra){if(rh==null||ra==null)return null;ph=Number(ph);pa=Number(pa);rh=Number(rh);ra=Number(ra);if(ph===rh&&pa===ra)return 5;if((ph-pa)===(rh-ra))return 3;if(sign(ph,pa)===sign(rh,ra))return 2;return 0}
function normalizeScorer(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]/g,'').replace(/\s+/g,' ').trim()}
function scorerPoints(p,m){if(!currentPool?.enable_scorer||!p?.scorer_prediction||!m?.real_scorers)return 0;const pick=normalizeScorer(p.scorer_prediction);const scorers=String(m.real_scorers).split(',').map(x=>normalizeScorer(x)).filter(Boolean);return scorers.includes(pick)?2:0}
function pointsForPrediction(p,m){const b=basePoints(p.pred_home,p.pred_away,m.real_home,m.real_away);return b==null?null:(p.is_joker?b*2:b)+scorerPoints(p,m)}
function isLocked(m){return new Date(m.match_date).getTime()<=Date.now()}
function isArchivedMatch(m){return Date.now()-new Date(m.match_date).getTime()>7*24*60*60*1000}
function activeMatches(){return matches.filter(m=>!isArchivedMatch(m))}
function archivedMatches(){return matches.filter(m=>isArchivedMatch(m))}
function currentPoolMemberIds(){return currentPool?poolMembers.filter(pm=>pm.pool_id===currentPool.id).map(pm=>pm.user_id):[]}
function poolUsers(){const ids=currentPoolMemberIds();return users.filter(u=>ids.includes(u.id))}
function poolPredictions(){if(!currentPool)return[];const ids=currentPoolMemberIds();return predictions.filter(p=>p.pool_id===currentPool.id&&ids.includes(p.user_id))}
function pred(mid){return poolPredictions().find(p=>p.user_id===currentUser?.id&&String(p.match_id)===String(mid))}
function jokerCount(){return currentUser&&currentPool?poolPredictions().filter(p=>p.user_id===currentUser.id&&p.is_joker).length:0}
function jokerLimit(){return 5}
function jokerUsed(){return jokerCount()>=jokerLimit()}
function myMembership(){return currentUser&&currentPool?poolMembers.find(pm=>pm.user_id===currentUser.id&&pm.pool_id===currentPool.id):null}
function canAdminPool(){return currentUser?.role==='admin'||currentPool?.created_by===currentUser?.id||myMembership()?.role==='admin'}
function saveSession(){try{localStorage.setItem(SESSION_KEY,JSON.stringify({userId:currentUser?.id||null,poolId:currentPool?.id||null}))}catch(e){}}
function clearSession(){try{localStorage.removeItem(SESSION_KEY)}catch(e){}}
function teamName(v){return safe(v)}

function normTeam(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim()}
const TEAM_ALIASES={"argentina":"ARG","arg":"ARG","canada":"CAN","canadá":"CAN","can":"CAN","brasil":"BRA","brazil":"BRA","bra":"BRA","espana":"ESP","españa":"ESP","spain":"ESP","esp":"ESP","francia":"FRA","france":"FRA","fra":"FRA","alemania":"GER","germany":"GER","ger":"GER","inglaterra":"ENG","england":"ENG","eng":"ENG","portugal":"POR","belgica":"BEL","bélgica":"BEL","belgium":"BEL","paises bajos":"NED","países bajos":"NED","holanda":"NED","netherlands":"NED","mexico":"MEX","méxico":"MEX","usa":"USA","estados unidos":"USA","eeuu":"USA","uruguay":"URU","colombia":"COL","croacia":"CRO","croatia":"CRO","marruecos":"MAR","morocco":"MAR","japon":"JPN","japón":"JPN","japan":"JPN","corea del sur":"KOR","south korea":"KOR","australia":"AUS","argelia":"ALG","algeria":"ALG","austria":"AUT","cabo verde":"CPV","costa de marfil":"CIV","cote divoire":"CIV","congo":"COD","congo dr":"COD","bosnia":"BIH","bosnia y herzegovina":"BIH","ghana":"GHA","egipto":"EGY","egypt":"EGY","iran":"IRN","irán":"IRN","iraq":"IRQ","irak":"IRQ","noruega":"NOR","norway":"NOR","senegal":"SEN","suiza":"SUI","switzerland":"SUI","tunez":"TUN","túnez":"TUN","turquia":"TUR","turquía":"TUR","uzbekistan":"UZB","uzbekistán":"UZB","qatar":"QAT","catar":"QAT","arabia saudi":"KSA","arabia saudí":"KSA","saudi arabia":"KSA","paraguay":"PAR","panama":"PAN","panamá":"PAN","ecuador":"ECU"}
function teamCodeForName(name){const n=normTeam(name);if(TEAM_ALIASES[n])return TEAM_ALIASES[n];const f=teamPlayers.find(p=>normTeam(p.team_name)===n||normTeam(p.team_code)===n);return f?.team_code||null}
function playersForMatch(m){const h=teamCodeForName(m.home_team),a=teamCodeForName(m.away_team);const codes=[h,a].filter(Boolean);return (codes.length?teamPlayers.filter(p=>codes.includes(p.team_code)):[]).sort((x,y)=>(x.team_code+x.position+x.player_name).localeCompare(y.team_code+y.position+y.player_name))}
function scorerSelectHtml(m,p,disabled){if(!currentPool?.enable_scorer)return'';const list=playersForMatch(m);if(!list.length)return `<label style="display:block;margin:10px 0">⚽ Pon un goleador del partido (+2 puntos)</label><input ${disabled?'disabled':''} id="scorer_${m.id}" value="${safe(p?.scorer_prediction||'')}" placeholder="Ejemplo: Messi"><p class="muted">Si no sale desplegable, el nombre del equipo no coincide con la plantilla.</p>`;return `<label style="display:block;margin:10px 0">⚽ Goleador del partido (+2 puntos)</label><select id="scorer_${m.id}" ${disabled?'disabled':''} style="width:100%;font-size:18px;padding:15px;border:2px solid #dbe3ef;border-radius:17px"><option value="">Sin goleador</option>${list.map(pl=>`<option value="${safe(pl.player_name)}" ${p?.scorer_prediction===pl.player_name?'selected':''}>${safe(pl.team_code)} · ${safe(pl.player_name)} ${pl.position==='PO'?'(portero)':''}</option>`).join('')}</select>`}
function realScorersHtml(m){const list=playersForMatch(m);if(!list.length)return `<label>Goleadores reales separados por coma</label><input id="real_scorers_${m.id}" value="${safe(m.real_scorers||'')}" placeholder="Ejemplo: Messi, J. ALVAREZ">`;const current=String(m.real_scorers||'').split(',').map(x=>normalizeScorer(x));return `<label>Goleadores reales</label><select id="real_scorers_${m.id}" multiple size="6" style="width:100%;font-size:16px;padding:12px;border:2px solid #dbe3ef;border-radius:17px">${list.map(pl=>`<option value="${safe(pl.player_name)}" ${current.includes(normalizeScorer(pl.player_name))?'selected':''}>${safe(pl.team_code)} · ${safe(pl.player_name)}</option>`).join('')}</select><p class="muted">Mantén Ctrl pulsado para seleccionar varios goleadores.</p>`}
function selectedRealScorers(mid){const sel=document.querySelector('#real_scorers_'+mid);if(!sel)return'';return sel.tagName==='SELECT'?Array.from(sel.selectedOptions).map(o=>o.value).join(','):(sel.value||'')}

async function loadData(doRender=true){if(!supabaseReady)return renderNoConfig();const [u,p,pm,m,pr,msg,tp]=await Promise.all([supabase.from('profiles').select('*'),supabase.from('pools').select('*').order('created_at',{ascending:false}),supabase.from('pool_members').select('*'),supabase.from('matches').select('*').order('match_date'),supabase.from('predictions').select('*'),supabase.from('messages').select('*').order('created_at',{ascending:true}).limit(200),supabase.from('team_players').select('*')]);users=u.data||[];pools=p.data||[];poolMembers=pm.data||[];matches=m.data||[];predictions=pr.data||[];messages=msg.data||[];teamPlayers=tp.data||[];if(currentUser)currentUser=users.find(x=>x.id===currentUser.id)||currentUser;if(currentPool)currentPool=pools.find(x=>x.id===currentPool.id)||currentPool;if(doRender)render()}
async function restoreSession(){try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return false;const s=JSON.parse(raw);if(!s.userId)return false;await loadData(false);currentUser=users.find(u=>u.id===s.userId)||null;if(!currentUser){clearSession();return false}currentPool=pools.find(p=>p.id===s.poolId)||null;tab=currentUser.role==='admin'?'porras':(currentPool?'partidos':'porras');render();return true}catch(e){clearSession();return false}}
function renderNoConfig(){app.innerHTML='<div class="app"><div class="card"><h1>Falta configurar Supabase</h1></div></div>'}
function loginView(){return `<div class="app"><div class="hero"><div><div class="kicker">MUNDIAL · APP PRIVADA</div><h1>Mi Porra<br><span>Tu Gloria</span></h1><p>Acierta el marcador, suma puntos y presume en la clasificación.</p></div><div class="ball">⚽</div></div><div class="card"><h2>Entrar</h2><label>Nick</label><input id="nick"><label>Email opcional</label><input id="email"><label>Contraseña</label><input id="pass" type="password"><button onclick="window.login()">Entrar</button><button class="blue" onclick="window.register()">Registrarme</button></div></div>`}
async function register(){const nick=document.querySelector('#nick').value.trim(),email=document.querySelector('#email').value.trim(),password=document.querySelector('#pass').value;if(!nick||!password)return alert('Pon nick y contraseña');const exists=await supabase.from('profiles').select('*').eq('nick',nick).maybeSingle();if(exists.data)return alert('Ese nick ya existe');let role='user';if(nick.toLowerCase()===ADMIN_NICK){if(password!==ADMIN_PASSWORD)return alert('Contraseña de admin incorrecta');role='admin'}const ins=await supabase.from('profiles').insert({nick,email,password,role,avatar:role==='admin'?'🛡️':'🙈'}).select().single();if(ins.error)return alert(ins.error.message);currentUser=ins.data;currentPool=null;tab='porras';saveSession();await loadData()}
async function login(){const nick=document.querySelector('#nick').value.trim(),password=document.querySelector('#pass').value;if(!nick||!password)return alert('Pon nick y contraseña');const res=await supabase.from('profiles').select('*').eq('nick',nick).eq('password',password).maybeSingle();if(!res.data)return alert('Usuario o contraseña incorrectos');currentUser=res.data;currentPool=null;tab='porras';saveSession();await loadData()}
function logout(){currentUser=null;currentPool=null;tab='porras';clearSession();render()}
function setTab(t){tab=t;saveSession();render()}
function tabs(){const poolLabel=currentPool?`<div class="card"><b>Porra actual:</b> ${safe(currentPool.name)} · Código: <b>${safe(currentPool.code)}</b> · Goleador: <b>${currentPool.enable_scorer?'Sí':'No'}</b>${currentPool.prizes?`<br><br><b>🏆 Premios:</b><br>${safe(currentPool.prizes).replace(/\n/g,'<br>')}`:''}</div>`:'';const adminTabs=`<div class="tabs"><button onclick="window.setTab('porras')">Todas las porras</button><button class="yellow" onclick="window.setTab('resultados')">Resultados globales</button><button class="blue" onclick="window.setTab('archivo')">Archivo</button><button class="blue" onclick="window.setTab('historial')">Historial</button><button class="red" onclick="window.logout()">Salir</button></div>`;const userTabs=`<div class="tabs"><button onclick="window.setTab('porras')">Mis porras</button><button onclick="window.setTab('partidos')">Partidos</button><button class="blue" onclick="window.setTab('normas')">Normas</button><button class="blue" onclick="window.setTab('clasificacion')">Clasificación</button><button class="blue" onclick="window.setTab('estadisticas')">Estadísticas</button><button class="blue" onclick="window.setTab('chat')">Chat</button><button class="blue" onclick="window.setTab('historial')">Historial</button><button class="blue" onclick="window.setTab('archivo')">Archivo</button>${canAdminPool()?`<button class="yellow" onclick="window.setTab('admin')">Admin</button>`:''}<button class="red" onclick="window.logout()">Salir</button></div>`;return `${currentUser?.role==='admin'?adminTabs:userTabs}<div class="card"><h2>${avatar(currentUser)} Hola, ${safe(currentUser.nick)}</h2><p>${currentUser?.role==='admin'?'Modo administrador':'El Mundial pasa cada cuatro años; las bromas al último de la porra duran mucho más.'}</p><button class="small blue" onclick="window.saveProfile()">Editar avatar</button></div>${poolLabel}`}
function poolsView(){const myIds=currentUser?.role==='admin'?pools.map(p=>p.id):poolMembers.filter(pm=>pm.user_id===currentUser.id).map(pm=>pm.pool_id);const list=pools.filter(p=>myIds.includes(p.id));return `<div class="card"><h2>${currentUser?.role==='admin'?'Todas las porras privadas':'🏆 Mis porras privadas'}</h2>${currentUser?.role!=='admin'?`<p class="muted">Crea una porra o únete con código.</p><button onclick="window.createPool()">➕ Crear porra privada</button><button class="blue" onclick="window.joinPool()">🔑 Unirme con código</button>`:''}${list.map(p=>`<div class="match"><h3>${safe(p.name)}</h3><p>Código: <b>${safe(p.code)}</b> · Participantes: <b>${poolMembers.filter(pm=>pm.pool_id===p.id).length}</b> · Joker: <b>${p.enable_joker?'Sí':'No'}</b> · Goleador: <b>${p.enable_scorer?'Sí':'No'}</b></p>${p.prizes?`<p><b>🏆 Premios:</b><br>${safe(p.prizes).replace(/\n/g,'<br>')}</p>`:''}<button onclick="window.selectPool('${p.id}')">Entrar en esta porra</button>${currentUser?.role!=='admin'?`<button class="red" onclick="window.leavePool('${p.id}')">Salir de esta porra</button>`:''}</div>`).join('')||'<p class="muted">No hay porras.</p>'}</div>`}
function selectPool(id){currentPool=pools.find(p=>String(p.id)===String(id))||null;tab=currentUser?.role==='admin'?'admin':'partidos';saveSession();render()}
async function createPool(){if(currentUser?.role==='admin')return alert('El admin no juega');const name=prompt('Nombre de la porra privada:');if(!name)return;let code=prompt('Código invitación. Vacío para automático:');if(!code)code=generateCode();code=code.trim().toUpperCase();const ex=await supabase.from('pools').select('*').eq('code',code).maybeSingle();if(ex.data)return alert('Ese código ya existe');const enable_joker=confirm('¿Activar Joker? Cada usuario tendrá 5 Jokers.');const enable_scorer=confirm('¿Activar goleador? Si acierta, +2 puntos.');const prizes=prompt('Premios de esta porra:','')||'';const ins=await supabase.from('pools').insert({name,code,created_by:currentUser.id,enable_joker,enable_scorer,prizes}).select().single();if(ins.error)return alert(ins.error.message);await supabase.from('pool_members').insert({pool_id:ins.data.id,user_id:currentUser.id,role:'admin'});currentPool=ins.data;tab='partidos';saveSession();await loadData()}
async function joinPool(){if(currentUser?.role==='admin')return alert('El admin no participa');const code=prompt('Código de la porra:');if(!code)return;const res=await supabase.from('pools').select('*').eq('code',code.trim().toUpperCase()).maybeSingle();if(!res.data)return alert('Código no encontrado');const exists=await supabase.from('pool_members').select('*').eq('pool_id',res.data.id).eq('user_id',currentUser.id).maybeSingle();if(!exists.data)await supabase.from('pool_members').insert({pool_id:res.data.id,user_id:currentUser.id,role:'user'});currentPool=res.data;tab='partidos';saveSession();await loadData()}
async function leavePool(id){if(!confirm('¿Salir de esta porra?'))return;await supabase.from('pool_members').delete().eq('pool_id',id).eq('user_id',currentUser.id);if(currentPool?.id===id)currentPool=null;tab='porras';saveSession();await loadData()}
function matchesView(){if(currentUser?.role==='admin')return `<div class="card"><h2>Modo administrador</h2><p>Usa Resultados globales.</p></div>`;if(!currentPool)return poolsView();return `<div class="card"><h2>Mis pronósticos</h2>${currentPool.enable_joker?`<div class="notice"><b>🃏 Joker:</b> te quedan ${jokerLimit()-jokerCount()}.</div>`:''}${currentPool.enable_scorer?`<div class="notice"><b>⚽ Goleador:</b> acierto +2 puntos.</div>`:''}${activeMatches().map(m=>{const p=pred(m.id),pt=p?pointsForPrediction(p,m):null,locked=isLocked(m),fieldsLocked=locked,jokerDisabled=fieldsLocked||!currentPool.enable_joker||(jokerUsed()&&!p?.is_joker);return `<div class="match"><span class="group">${safe(m.group_name)}</span><div class="teams">${teamName(m.home_team)} vs ${teamName(m.away_team)}</div><div class="muted">${new Date(m.match_date).toLocaleString('es-ES')}</div><p><span class="badge ${locked?'closed':''}">${locked?'🔒 Partido iniciado':'Abierto'}</span><span class="badge">${p?'Guardado':'Sin guardar'}</span><span class="badge">${pt===null?'Pendiente':pt+' pts'}</span>${p?.is_joker?'<span class="badge-gold">🃏 Joker</span>':''}</p><div class="score"><div><label>${teamName(m.home_team)}</label><input ${fieldsLocked?'disabled':''} type="number" min="0" id="ph_${m.id}" value="${p?.pred_home??''}"></div><div style="font-weight:900;padding-bottom:17px">-</div><div><label>${teamName(m.away_team)}</label><input ${fieldsLocked?'disabled':''} type="number" min="0" id="pa_${m.id}" value="${p?.pred_away??''}"></div></div>${currentPool.enable_joker?`<label style="display:block;margin:10px 0"><input type="checkbox" id="joker_${m.id}" ${p?.is_joker?'checked':''} ${jokerDisabled?'disabled':''}> 🃏 Usar Joker</label>`:''}${scorerSelectHtml(m,p,fieldsLocked)}${locked?`<p class="muted"><b>Partido iniciado:</b> no se puede modificar.</p>`:`<button class="small" onclick="window.savePrediction('${m.id}')">Guardar pronóstico</button>`}<p class="muted">Resultado real: <b>${m.real_home===null?'Pendiente':m.real_home+' - '+m.real_away}</b></p>${locked?matchPoolPredictions(m.id):''}</div>`}).join('')}</div>`}
function matchPoolPredictions(mid){if(!currentPool)return'';const rows=poolUsers().filter(u=>u.role!=='admin').map(u=>({user:u,prediction:poolPredictions().find(pr=>pr.user_id===u.id&&String(pr.match_id)===String(mid))}));return `<div class="notice"><h3>👀 Pronósticos de este partido</h3>${rows.map(r=>`<div class="ranking"><div>${avatar(r.user)}</div><div>${safe(r.user.nick)}${r.prediction?.is_joker?'<br><span class="badge-gold">🃏 Joker</span>':''}${r.prediction?.scorer_prediction?`<br><span class="badge">⚽ ${safe(r.prediction.scorer_prediction)}</span>`:''}</div><div>${r.prediction?`<b>${r.prediction.pred_home} - ${r.prediction.pred_away}</b>`:'<span class="muted">Sin pronóstico</span>'}</div></div>`).join('')}</div>`}
async function savePrediction(mid){if(currentUser?.role==='admin')return alert('El admin no pronostica');if(!currentPool)return alert('Selecciona una porra');const m=matches.find(x=>String(x.id)===String(mid));if(!m)return;if(isLocked(m))return alert('Este partido ya ha empezado');const ph=parseInt(document.querySelector('#ph_'+mid).value,10),pa=parseInt(document.querySelector('#pa_'+mid).value,10);if(isNaN(ph)||isNaN(pa)||ph<0||pa<0)return alert('Pon resultado válido');const wants=!!document.querySelector('#joker_'+mid)?.checked;if(wants&&jokerUsed()&&!pred(mid)?.is_joker)return alert('Ya has usado tus 5 Jokers');const scorer=document.querySelector('#scorer_'+mid)?.value.trim()||null;const ex=pred(mid);if(ex)await supabase.from('predictions').update({pred_home:ph,pred_away:pa,is_joker:wants,scorer_prediction:scorer}).eq('id',ex.id);else await supabase.from('predictions').insert({pool_id:currentPool.id,user_id:currentUser.id,match_id:mid,pred_home:ph,pred_away:pa,is_joker:wants,scorer_prediction:scorer});await loadData()}
function rulesView(){if(!currentPool)return poolsView();return `<div class="card"><h2>📖 Normas</h2><div class="rule"><h3>🎯 Exacto: 5 puntos</h3></div><div class="rule"><h3>⚽ Diferencia correcta: 3 puntos</h3></div><div class="rule"><h3>✅ Signo: 2 puntos</h3></div><div class="rule"><h3>🃏 Joker</h3><p>${currentPool.enable_joker?'5 Jokers por usuario. Puntúan doble.':'Desactivado.'}</p></div><div class="rule"><h3>⚽ Goleador</h3><p>${currentPool.enable_scorer?'Si aciertas un goleador, +2 puntos.':'Desactivado.'}</p></div></div>`}
function userStats(u){let total=0,exact=0,diff=0,sg=0,played=0,jokers=0,scorersOk=0;predictions.filter(p=>p.user_id===u.id&&p.pool_id===currentPool?.id).forEach(p=>{const m=matches.find(x=>String(x.id)===String(p.match_id));if(!m)return;const pts=pointsForPrediction(p,m);if(pts===null)return;total+=pts;played++;if(p.is_joker)jokers++;if(scorerPoints(p,m)>0)scorersOk++;const b=basePoints(p.pred_home,p.pred_away,m.real_home,m.real_away);if(b===5)exact++;else if(b===3)diff++;else if(b===2)sg++});return{total,exact,diff,sg,played,jokers,scorersOk}}
function rankingView(){if(!currentPool)return poolsView();const rows=poolUsers().filter(u=>u.role!=='admin').map(u=>({u,...userStats(u)})).sort((a,b)=>b.total-a.total||b.exact-a.exact);return `<div class="card"><h2>🏆 Clasificación</h2>${rows.map((r,i)=>`<div class="ranking"><div>${i+1}</div><div>${avatar(r.u)} ${safe(r.u.nick)}<br><span class="muted">Exactos: ${r.exact} · Dif: ${r.diff} · Signo: ${r.sg} · Joker: ${r.jokers} · Goleadores: ${r.scorersOk}</span></div><div>${r.total} pts</div></div>`).join('')||'<p class="muted">Sin participantes.</p>'}</div>`}
function statsView(){if(!currentPool)return poolsView();return `<div class="card"><h2>📊 Estadísticas</h2><p>Participantes: <b>${poolUsers().filter(u=>u.role!=='admin').length}</b></p><p>Pronósticos: <b>${poolPredictions().length}</b></p></div>`}
function chatView(){if(!currentPool)return poolsView();const ms=messages.filter(m=>m.pool_id===currentPool.id);return `<div class="card"><h2>💬 Chat</h2><div class="match">${ms.map(m=>`<p><b>${safe(users.find(u=>u.id===m.user_id)?.nick||'Usuario')}:</b> ${safe(m.body)}</p>`).join('')||'<p class="muted">Sin mensajes.</p>'}</div><input id="chatmsg" placeholder="Mensaje"><button onclick="window.sendMessage()">Enviar</button></div>`}
async function sendMessage(){const body=document.querySelector('#chatmsg').value.trim();if(!body||!currentPool)return;await supabase.from('messages').insert({pool_id:currentPool.id,user_id:currentUser.id,body});await loadData()}
function historyView(){return `<div class="card"><h2>📜 Historial</h2>${matches.filter(m=>m.real_home!==null&&!isArchivedMatch(m)).map(m=>`<div class="match"><b>${teamName(m.home_team)} ${m.real_home} - ${m.real_away} ${teamName(m.away_team)}</b><div class="muted">${new Date(m.match_date).toLocaleString('es-ES')}</div></div>`).join('')||'<p class="muted">Sin resultados recientes.</p>'}</div>`}
function archiveView(){const list=archivedMatches();return `<div class="card"><h2>📦 Archivo</h2>${list.map(m=>`<div class="match"><span class="group">${safe(m.group_name)}</span><div class="teams">${teamName(m.home_team)} vs ${teamName(m.away_team)}</div><p>Resultado: <b>${m.real_home===null?'Pendiente':m.real_home+' - '+m.real_away}</b></p>${currentPool?matchPoolPredictions(m.id):''}</div>`).join('')||'<p class="muted">Sin partidos archivados.</p>'}</div>`}
function globalResultsView(){if(currentUser?.role!=='admin')return `<div class="card"><h2>Acceso no permitido</h2></div>`;const list=activeMatches();const renderMatch=m=>`<div class="adminrow"><b>${safe(m.group_name)} · ${teamName(m.home_team)} vs ${teamName(m.away_team)}</b><div class="muted">${new Date(m.match_date).toLocaleString('es-ES')}</div><div class="score"><div><label>${teamName(m.home_team)}</label><input type="number" min="0" id="grh_${m.id}" value="${m.real_home??''}"></div><div style="font-weight:900;padding-bottom:17px">-</div><div><label>${teamName(m.away_team)}</label><input type="number" min="0" id="gra_${m.id}" value="${m.real_away??''}"></div></div>${realScorersHtml(m)}<button class="small" onclick="window.saveGlobalReal('${m.id}')">Guardar resultado global</button><button class="small red" onclick="window.resetGlobalReal('${m.id}')">Reset</button></div>`;return `<div class="card"><h2>⚽ Resultados globales</h2>${list.map(renderMatch).join('')}</div>`}
async function saveGlobalReal(mid){const rh=parseInt(document.querySelector('#grh_'+mid).value,10),ra=parseInt(document.querySelector('#gra_'+mid).value,10);if(isNaN(rh)||isNaN(ra)||rh<0||ra<0)return alert('Pon resultado válido');await supabase.from('matches').update({real_home:rh,real_away:ra,real_scorers:selectedRealScorers(mid)}).eq('id',mid);await loadData();alert('Resultado guardado')}
async function resetGlobalReal(mid){if(!confirm('¿Borrar resultado?'))return;await supabase.from('matches').update({real_home:null,real_away:null,real_scorers:''}).eq('id',mid);await loadData()}
function adminView(){if(!currentPool)return poolsView();return `<div class="card"><h2>Admin · ${safe(currentPool.name)}</h2><button class="yellow" onclick="window.updatePoolSettings()">⚙️ Joker / Goleador / Premios</button><h3>Participantes</h3>${poolUsers().map(u=>`<p>${avatar(u)} ${safe(u.nick)} ${u.role==='admin'?'(admin)':''}</p>`).join('')}</div>`}
async function updatePoolSettings(){if(!currentPool)return;const enable_joker=confirm('¿Activar Joker?');const enable_scorer=confirm('¿Activar goleador?');const prizes=prompt('Premios:',currentPool.prizes||'')||'';await supabase.from('pools').update({enable_joker,enable_scorer,prizes}).eq('id',currentPool.id);await loadData()}
async function saveProfile(){const av=prompt('Emoji avatar:',currentUser.avatar||'🙈');if(!av)return;await supabase.from('profiles').update({avatar:av}).eq('id',currentUser.id);await loadData()}
function render(){document.title='MI PORRA';if(!currentUser){app.innerHTML=loginView();return}let content='';try{content=tab==='porras'?poolsView():tab==='partidos'?matchesView():tab==='normas'?rulesView():tab==='clasificacion'?rankingView():tab==='estadisticas'?statsView():tab==='chat'?chatView():tab==='historial'?historyView():tab==='archivo'?archiveView():tab==='resultados'?globalResultsView():tab==='admin'?adminView():poolsView()}catch(e){console.error(e);content=`<div class="card"><h2>Error</h2><p>${safe(e.message)}</p><button onclick="window.setTab('porras')">Volver</button></div>`}app.innerHTML=`<div class="app">${tabs()}${content}</div>`}
Object.assign(window,{login,register,logout,setTab,selectPool,createPool,joinPool,leavePool,savePrediction,saveGlobalReal,resetGlobalReal,updatePoolSettings,saveProfile,sendMessage})
document.title='MI PORRA';restoreSession().then(ok=>{if(!ok)loadData()})
